apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  steps:
    - name: checkout
      image: cgr.dev/chainguard/git
      workingdir: /workspace
      script: |
        git clone https://github.com/chainguard-dev/go-demo
    - name: build
      image: cgr.dev/chainguard/ko
      workingDir: /workspace/go-demo
      env:
        - name: KO_DOCKER_REPO
          value: ttl.sh/wlynch/demo
      script: |
        ko build . > $(results.IMAGES.path)
    - name: sign
      image: cgr.dev/chainguard/cosign
      volumeMounts:
        - name: oidc-sigstore
          mountPath: "/var/run/sigstore/cosign"
          readOnly: true
      script: |
        cosign sign -y `cat $(results.IMAGES.path)`
  volumes:
  - name: oidc-sigstore
    projected:
      sources:
      - serviceAccountToken:
          audience: sigstore
          expirationSeconds: 600
          path: oidc-token
  results:
    - name: IMAGES
