apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: echo
      image: cgr.dev/chainguard/alpine-base:latest-20221218
      script: |
        echo "Hello World!"
    - name: echo2
      image: cgr.dev/chainguard/alpine-base:latest-20221219
      script: |
        echo "Hello World!"
